In [1]:
import numpy as np

In [5]:
x = np.array(["A",33,45,67])
print(x)
print(type(x))
print(x.dtype)


['A' '33' '45' '67']
<class 'numpy.ndarray'>
<U11


In [17]:
#create a 2d array
a2 = np.array([[23,45],[34,65]])
print(a2)
print(type(a2))
print(a2.shape)

[[23 45]
 [34 65]]
<class 'numpy.ndarray'>
(2, 2)


In [36]:
#reshape array
a = np.array([22,33,44,55])
b = a.reshape(2,2)
print(b)
print(type(a))

[[22 33]
 [44 55]]
<class 'numpy.ndarray'>


In [44]:
c = np.arange(1230,1234)
print(c)
print(type(c))

[1230 1231 1232 1233]
<class 'numpy.ndarray'>


In [54]:
#mathematical operation on rows and columns
a2=np.array([[3,4,5],[3,55,6],[33,44,50]])
a2

array([[ 3,  4,  5],
       [ 3, 55,  6],
       [33, 44, 50]])

In [56]:
print(a2.sum(axis = 1))
print(a2.sum(axis = 0))

[ 12  64 127]
[ 39 103  61]


In [58]:
a2
print(np.mean(a2, axis = 1))
print(np.mean(a2, axis = 0))

[ 4.         21.33333333 42.33333333]
[13.         34.33333333 20.33333333]


In [60]:
#matrix operations
a3=np.array([[3,4,5],[3,55,6],[33,44,50]])
print(a3)
np.fill_diagonal(a3,0)



[[ 3  4  5]
 [ 3 55  6]
 [33 44 50]]


In [72]:
import numpy as np
a = np.array([[22,33],[33,55]])
b = np.array([[22,12],[33,47]])
c = np.matmul(a,b)
print(c)


[[1573 1815]
 [2541 2981]]


In [74]:
print(a.T)
print(b.T)


[[22 33]
 [33 55]]
[[22 33]
 [12 47]]


In [84]:
a4 = np.array([[333,555,666],[111,222,999],[123,456,789],[44,25,69]])
a4

array([[333, 555, 666],
       [111, 222, 999],
       [123, 456, 789],
       [ 44,  25,  69]])

In [90]:
#slicing of array
a4[:,2:]

array([[666],
       [999],
       [789],
       [ 69]])

In [104]:
a4[0:,1:]

array([[555, 666],
       [222, 999],
       [456, 789],
       [ 25,  69]])

In [106]:
a4[1:3,0:2]

array([[111, 222],
       [123, 456]])